apiVersion: v1
kind: Service
metadata:
  name: preprod-api-gateway
  namespace: studed
spec:
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: preprod-api-gateway
  namespace: studed
subsets:
  - addresses:
      - ip: 10.1.0.154
    ports:
      - port: 8080
