package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/studed/api-gateway/graph/model"
	"github.com/studed/api-gateway/internal/events"
	"github.com/studed/api-gateway/internal/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	payload, err := r.AuthClient.Register(ctx, input)
	if err != nil {
		return nil, err
	}
	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)
	return payload, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	payload, err := r.AuthClient.Login(ctx, input)
	if err != nil {
		return nil, err
	}
	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)

	// Advance the daily-login streak; streak failures never block login.
	if payload.User != nil {
		if streak, err := r.GamificationClient.GetUserStreak(ctx, payload.User.ID); err == nil {
			payload.User.Streak = streak
		}
	}

	return payload, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	if refreshToken == "" {
		req, ok := middleware.RequestFromContext(ctx)
		if ok {
			if cookie, err := req.Cookie("refresh_token"); err == nil {
				refreshToken = cookie.Value
			}
		}
	}

	if refreshToken == "" {
		return nil, errors.New("refresh token is required")
	}

	payload, err := r.AuthClient.RefreshToken(ctx, refreshToken)
	if err != nil {
		return nil, err
	}

	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)
	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	w, ok := middleware.ResponseWriterFromContext(ctx)
	if !ok {
		return true, nil
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "access_token",
		Value:    "",
		HttpOnly: true,
		Secure:   false,
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
		MaxAge:   -1,
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "refresh_token",
		Value:    "",
		HttpOnly: true,
		Secure:   false,
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
		MaxAge:   -1,
	})

	return true, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CreateCourseInput) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateCourse(ctx, userCtx.UserID, input)
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, id string, input model.UpdateCourseInput) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateCourse(ctx, userCtx.UserID, id, input)
}

// PublishCourse is the resolver for the publishCourse field.
func (r *mutationResolver) PublishCourse(ctx context.Context, id string) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishCourse(ctx, userCtx.UserID, id)
}

// CreateLesson is the resolver for the createLesson field.
func (r *mutationResolver) CreateLesson(ctx context.Context, courseID string, input model.CreateLessonInput) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateLesson(ctx, userCtx.UserID, courseID, input)
}

// UpdateLesson is the resolver for the updateLesson field.
func (r *mutationResolver) UpdateLesson(ctx context.Context, id string, input model.UpdateLessonInput) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateLesson(ctx, userCtx.UserID, id, input)
}

// PublishLesson is the resolver for the publishLesson field.
func (r *mutationResolver) PublishLesson(ctx context.Context, id string) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishLesson(ctx, userCtx.UserID, id)
}

// CreateWave is the resolver for the createWave field.
func (r *mutationResolver) CreateWave(ctx context.Context, lessonID string, input model.CreateWaveInput) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateWave(ctx, userCtx.UserID, lessonID, input)
}

// UpdateWave is the resolver for the updateWave field.
func (r *mutationResolver) UpdateWave(ctx context.Context, id string, input model.UpdateWaveInput) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateWave(ctx, userCtx.UserID, id, input)
}

// PublishWave is the resolver for the publishWave field.
func (r *mutationResolver) PublishWave(ctx context.Context, id string) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishWave(ctx, userCtx.UserID, id)
}

// SubmitWaveAnswers is the resolver for the submitWaveAnswers field.
func (r *mutationResolver) SubmitWaveAnswers(ctx context.Context, waveID string, answers []*model.AnswerInput) (*model.WaveResult, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	result, err := r.ProgressClient.SubmitWaveAnswers(ctx, userCtx.UserID, waveID, answers)
	if err != nil {
		return nil, err
	}

	if result.Passed {
		if userCtx.FullName == "" {
			return nil, fmt.Errorf("full name is empty in user context")
		}

		// Always update the global leaderboard.
		if _, err := r.GamificationClient.UpdateLeaderboard(ctx, userCtx.UserID, userCtx.FullName, result.TotalXp, model.LeaderboardScopeGlobal, "", nil); err != nil {
			return nil, fmt.Errorf("failed to update global leaderboard: %w", err)
		}

		// Resolve the wave's courseID for the course-scoped leaderboard.
		courseID, err := r.CourseClient.GetWaveCourseID(ctx, waveID)
		if err == nil && courseID != "" {
			if _, err := r.GamificationClient.UpdateLeaderboard(ctx, userCtx.UserID, userCtx.FullName, result.TotalXp, model.LeaderboardScopeCourse, courseID, nil); err != nil {
				return nil, fmt.Errorf("failed to update course leaderboard: %w", err)
			}
		}

		// Resolve the student's grade for the grade-scoped leaderboard
		// (grade is fetched from auth-service, NOT carried in the JWT).
		authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID)
		if err == nil && authUser.Grade != nil {
			if _, err := r.GamificationClient.UpdateLeaderboard(ctx, userCtx.UserID, userCtx.FullName, result.TotalXp, model.LeaderboardScopeGrade, "", authUser.Grade); err != nil {
				return nil, fmt.Errorf("failed to update grade leaderboard: %w", err)
			}
		}

		r.publishWaveEvents(ctx, userCtx, waveID, courseID, result)
	}

	return result, nil
}

// publishWaveEvents emits real-time wave/leaderboard events; publish
// failures never fail the submission.
func (r *mutationResolver) publishWaveEvents(ctx context.Context, userCtx middleware.UserContext, waveID, courseID string, result *model.WaveResult) {
	if r.Events == nil {
		return
	}

	_ = r.Events.Publish(ctx, events.ChannelWaveCompleted, events.WaveCompletedEvent{
		UserID:          userCtx.UserID,
		WaveID:          waveID,
		Score:           int32(result.Score),
		CompletedAtUnix: time.Now().Unix(),
	})

	scopes := []struct {
		scope    model.LeaderboardScope
		courseID string
	}{
		{model.LeaderboardScopeGlobal, ""},
	}
	if courseID != "" {
		scopes = append(scopes, struct {
			scope    model.LeaderboardScope
			courseID string
		}{model.LeaderboardScopeCourse, courseID})
	}
	for _, sc := range scopes {
		var cid *string
		if sc.courseID != "" {
			c := sc.courseID
			cid = &c
		}
		rank, err := r.GamificationClient.GetMyRank(ctx, userCtx.UserID, sc.scope, cid, nil)
		if err != nil {
			rank = 0
		}
		_ = r.Events.Publish(ctx, events.ChannelLeaderboard, events.LeaderboardUpdatedEvent{
			Scope:    string(sc.scope),
			CourseID: sc.courseID,
			UserID:   userCtx.UserID,
			FullName: userCtx.FullName,
			TotalXp:  int32(result.TotalXp),
			Rank:     int32(rank),
		})
	}
}

// EnrollInCourse is the resolver for the enrollInCourse field.
func (r *mutationResolver) EnrollInCourse(ctx context.Context, courseID string) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	course, err := r.CourseClient.GetCourseWithLessons(ctx, courseID)
	if err != nil {
		return nil, err
	}

	// Allow student enrollment in any course, removing restrictive grade mismatch check
	if userCtx.Role == "STUDENT" {
		_, err := r.AuthClient.GetUser(ctx, userCtx.UserID)
		if err != nil {
			return nil, fmt.Errorf("failed to verify student profile: %w", err)
		}
	}

	if _, err := r.ProgressClient.EnrollInCourse(ctx, userCtx.UserID, courseID); err != nil {
		return nil, err
	}

	progress, err := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, courseID)
	if err != nil {
		return nil, fmt.Errorf("failed to load progress: %w", err)
	}

	course.MyProgress = progress

	return course, nil
}

// GenerateLearnBlocks is the resolver for the generateLearnBlocks field.
func (r *mutationResolver) GenerateLearnBlocks(ctx context.Context, prompt string, language *string, grade *model.Grade) ([]*model.LearnBlock, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}
	if r.AIClient == nil {
		return nil, errors.New("AI service is not configured")
	}

	return r.AIClient.GenerateLearnBlocks(ctx, prompt, language, grade)
}

// GenerateEvaluateBlocks is the resolver for the generateEvaluateBlocks field.
func (r *mutationResolver) GenerateEvaluateBlocks(ctx context.Context, content string, count *int) ([]*model.EvaluateBlock, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}
	if r.AIClient == nil {
		return nil, errors.New("AI service is not configured")
	}

	return r.AIClient.GenerateEvaluateBlocks(ctx, content, count)
}

// TranslateContent is the resolver for the translateContent field.
func (r *mutationResolver) TranslateContent(ctx context.Context, content string, targetLanguage string) (string, error) {
	if _, err := requireUser(ctx); err != nil {
		return "", err
	}
	if r.AIClient == nil {
		return "", errors.New("AI service is not configured")
	}

	return r.AIClient.TranslateContent(ctx, content, targetLanguage)
}

// CreateSubscription is the resolver for the createSubscription field.
func (r *mutationResolver) CreateSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.UserSubscription, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.PaymentClient == nil {
		return nil, errors.New("payments are not configured")
	}

	return r.PaymentClient.CreateSubscription(ctx, userCtx.UserID, input.Tier)
}

// CancelSubscription is the resolver for the cancelSubscription field.
func (r *mutationResolver) CancelSubscription(ctx context.Context) (*model.UserSubscription, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.PaymentClient == nil {
		return nil, errors.New("payments are not configured")
	}

	return r.PaymentClient.CancelSubscription(ctx, userCtx.UserID)
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateMeInput) (*model.User, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedUser, err := r.AuthClient.UpdateUser(ctx, userCtx.UserID, input)
	if err != nil {
		return nil, err
	}

	// Fetch XP & Streaks to populate model fully
	totalXp, _ := r.GamificationClient.GetUserXp(ctx, userCtx.UserID)
	streak, _ := r.GamificationClient.GetUserStreak(ctx, userCtx.UserID)
	updatedUser.TotalXp = totalXp
	updatedUser.Streak = streak

	return updatedUser, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userCtx, ok := middleware.UserFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	totalXp, _ := r.GamificationClient.GetUserXp(ctx, userCtx.UserID)
	streak, _ := r.GamificationClient.GetUserStreak(ctx, userCtx.UserID)

	var grade *model.Grade
	if authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID); err == nil {
		grade = authUser.Grade
	}

	var subscription *model.UserSubscription
	if r.PaymentClient != nil {
		// A "not found" response just means the user never subscribed — not a hard error.
		if sub, err := r.PaymentClient.GetSubscription(ctx, userCtx.UserID); err == nil {
			subscription = sub
		}
	}

	return &model.User{
		ID:                userCtx.UserID,
		Email:             userCtx.Email,
		FullName:          userCtx.FullName,
		Role:              model.Role(userCtx.Role),
		Grade:             grade,
		PreferredLanguage: userCtx.PreferredLanguage,
		TotalXp:           totalXp,
		Streak:            streak,
		Subscription:      subscription,
	}, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context, filter *model.CourseFilter, pagination *model.PaginationInput) (*model.CourseConnection, error) {
	if filter == nil {
		filter = &model.CourseFilter{}
	}

	userCtx, ok := middleware.UserFromContext(ctx)
	isEducator := ok && (userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN")

	var educatorID string
	if ok && isEducator {
		educatorID = userCtx.UserID
	} else if filter.IsPublished == nil {
		published := true
		filter.IsPublished = &published
	}

	return r.CourseClient.ListCourses(ctx, filter, educatorID)
}

// MyEnrollments is the resolver for the myEnrollments field.
func (r *queryResolver) MyEnrollments(ctx context.Context) ([]*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	courses, err := r.ProgressClient.GetEnrolledCourses(ctx, userCtx.UserID)
	if err != nil {
		return nil, err
	}

	for _, course := range courses {
		progress, _ := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, course.ID)
		course.MyProgress = progress
		r.populateWavesProgress(ctx, userCtx.UserID, course)
	}

	return courses, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	course, err := r.CourseClient.GetCourseWithLessons(ctx, id)
	if err != nil {
		return nil, err
	}

	isEducatorOrAdmin := userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN"
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own this course")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}

		// Enrollment check removed to allow viewing course details

		// Filter out unpublished lessons and waves
		publishedLessons := make([]*model.Lesson, 0, len(course.Lessons))
		for _, lesson := range course.Lessons {
			if lesson.IsPublished {
				publishedWaves := make([]*model.Wave, 0, len(lesson.Waves))
				for _, wave := range lesson.Waves {
					if wave.IsPublished {
						publishedWaves = append(publishedWaves, wave)
					}
				}
				lesson.Waves = publishedWaves
				publishedLessons = append(publishedLessons, lesson)
			}
		}
		course.Lessons = publishedLessons
		r.populateWavesProgress(ctx, userCtx.UserID, course)
	}

	progress, _ := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, id)
	course.MyProgress = progress

	return course, nil
}

// Lesson is the resolver for the lesson field.
func (r *queryResolver) Lesson(ctx context.Context, id string) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	lesson, err := r.CourseClient.GetLessonWithWaves(ctx, id)
	if err != nil {
		return nil, err
	}

	if lesson.Course == nil {
		return nil, errors.New("lesson has no associated course")
	}

	course, err := r.CourseClient.GetCourse(ctx, lesson.Course.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve course for lesson: %w", err)
	}

	isEducatorOrAdmin := userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN"
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own the course for this lesson")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}
		if !lesson.IsPublished {
			return nil, errors.New("forbidden: lesson is not published")
		}

		enrolled, err := r.ProgressClient.IsEnrolled(ctx, userCtx.UserID, course.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to check enrollment: %w", err)
		}
		if !enrolled {
			return nil, errors.New("forbidden: not enrolled in the course for this lesson")
		}

		// Filter out unpublished waves
		publishedWaves := make([]*model.Wave, 0, len(lesson.Waves))
		for _, wave := range lesson.Waves {
			if wave.IsPublished {
				publishedWaves = append(publishedWaves, wave)
			}
		}
		lesson.Waves = publishedWaves
	}

	return lesson, nil
}

// Wave is the resolver for the wave field.
func (r *queryResolver) Wave(ctx context.Context, id string) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	wave, err := r.CourseClient.GetWave(ctx, id)
	if err != nil {
		return nil, err
	}

	if wave.Lesson == nil {
		return nil, errors.New("wave has no associated lesson")
	}

	lesson, err := r.CourseClient.GetLesson(ctx, wave.Lesson.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve lesson for wave: %w", err)
	}

	if lesson.Course == nil {
		return nil, errors.New("lesson has no associated course")
	}

	course, err := r.CourseClient.GetCourse(ctx, lesson.Course.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve course for wave: %w", err)
	}

	isEducatorOrAdmin := userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN"
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own the course for this wave")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}
		if !lesson.IsPublished {
			return nil, errors.New("forbidden: lesson is not published")
		}
		if !wave.IsPublished {
			return nil, errors.New("forbidden: wave is not published")
		}

		enrolled, err := r.ProgressClient.IsEnrolled(ctx, userCtx.UserID, course.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to check enrollment: %w", err)
		}
		if !enrolled {
			return nil, errors.New("forbidden: not enrolled in the course for this wave")
		}
	}

	progress, _ := r.ProgressClient.GetWaveProgress(ctx, userCtx.UserID, id)
	wave.MyProgress = progress
	wave.Lesson = lesson

	return wave, nil
}

// Progress is the resolver for the progress field.
func (r *queryResolver) Progress(ctx context.Context, courseID *string) ([]*model.LessonProgress, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	if courseID == nil || *courseID == "" {
		return nil, errors.New("course id is required")
	}

	return r.ProgressClient.GetCourseProgress(ctx, userCtx.UserID, *courseID)
}

// WaveProgress is the resolver for the waveProgress field.
func (r *queryResolver) WaveProgress(ctx context.Context, waveID string) (*model.WaveProgress, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	return r.ProgressClient.GetWaveProgress(ctx, userCtx.UserID, waveID)
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, scope model.LeaderboardScope, courseID *string, grade *model.Grade) ([]*model.LeaderboardEntry, error) {
	return r.GamificationClient.GetLeaderboard(ctx, scope, courseID, grade, 100)
}

// MyRank is the resolver for the myRank field.
func (r *queryResolver) MyRank(ctx context.Context, scope model.LeaderboardScope, courseID *string) (*int, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var grade *model.Grade
	if scope == model.LeaderboardScopeGrade {
		authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID)
		if err != nil {
			return nil, err
		}
		grade = authUser.Grade
	}

	rank, err := r.GamificationClient.GetMyRank(ctx, userCtx.UserID, scope, courseID, grade)
	if err != nil {
		return nil, err
	}

	return &rank, nil
}

// Achievements is the resolver for the achievements field.
func (r *queryResolver) Achievements(ctx context.Context) ([]*model.Achievement, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	return r.GamificationClient.GetAchievements(ctx, userCtx.UserID)
}

// LeaderboardUpdated is the resolver for the leaderboardUpdated field.
func (r *subscriptionResolver) LeaderboardUpdated(ctx context.Context, scope model.LeaderboardScope, courseID *string) (<-chan *model.LeaderboardEntry, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	if _, err := requireUser(ctx); err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.LeaderboardUpdatedEvent](ctx, r.Events, events.ChannelLeaderboard)
	out := make(chan *model.LeaderboardEntry, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.Scope != string(scope) {
				continue
			}
			if scope == model.LeaderboardScopeCourse && (courseID == nil || e.CourseID != *courseID) {
				continue
			}
			out <- &model.LeaderboardEntry{
				Rank:    int(e.Rank),
				User:    &model.User{ID: e.UserID, FullName: e.FullName},
				TotalXp: int(e.TotalXp),
			}
		}
	}()
	return out, nil
}

// XpGained is the resolver for the xpGained field.
func (r *subscriptionResolver) XpGained(ctx context.Context) (<-chan *model.XpEvent, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.XpAwardedEvent](ctx, r.Events, events.ChannelXp)
	out := make(chan *model.XpEvent, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			out <- &model.XpEvent{
				WaveID:  e.SourceID,
				Amount:  int(e.Amount),
				TotalXp: int(e.TotalXp),
				Reason:  e.Reason,
			}
		}
	}()
	return out, nil
}

// AchievementUnlocked is the resolver for the achievementUnlocked field.
func (r *subscriptionResolver) AchievementUnlocked(ctx context.Context) (<-chan *model.Achievement, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.AchievementUnlockedEvent](ctx, r.Events, events.ChannelAchievement)
	out := make(chan *model.Achievement, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			achievement := &model.Achievement{
				ID:          e.ID,
				Name:        e.Name,
				Description: e.Description,
				UnlockedAt:  time.Unix(e.UnlockedAtUnix, 0),
			}
			if e.IconURL != "" {
				iconURL := e.IconURL
				achievement.IconURL = &iconURL
			}
			out <- achievement
		}
	}()
	return out, nil
}

// WaveCompleted is the resolver for the waveCompleted field.
func (r *subscriptionResolver) WaveCompleted(ctx context.Context) (<-chan *model.WaveProgress, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.WaveCompletedEvent](ctx, r.Events, events.ChannelWaveCompleted)
	out := make(chan *model.WaveProgress, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			score := int(e.Score)
			completedAt := time.Unix(e.CompletedAtUnix, 0)
			out <- &model.WaveProgress{
				Status:       model.ProgressStatusCompleted,
				HighestScore: &score,
				CompletedAt:  &completedAt,
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
