package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/studed/api-gateway/graph/model"
	"github.com/studed/api-gateway/internal/client"
	"github.com/studed/api-gateway/internal/events"
	"github.com/studed/api-gateway/internal/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	payload, err := r.AuthClient.Register(ctx, input)
	if err != nil {
		return nil, err
	}
	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)
	return payload, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	payload, err := r.AuthClient.Login(ctx, input)
	if err != nil {
		return nil, err
	}
	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)

	// Attach the current streak and XP so the client does not store totalXp=0 at
	// sign-in and render 0 until the first `me` query lands. This only reads:
	// signing in is not learning, so it does not advance the streak.
	// Gamification failures never block login.
	if payload.User != nil {
		if streak, err := r.GamificationClient.GetUserStreak(ctx, payload.User.ID); err == nil {
			payload.User.Streak = streak.Current
			payload.User.LongestStreak = streak.Longest
			payload.User.LastActiveAt = streak.LastActiveAt
		}
		// Record who this user is for ranking purposes. Signing in is not
		// learning and earns nothing, but it is a good moment to keep the
		// display name current: a student who has never passed a wave since
		// the name was first stored would otherwise rank as "Student Scholar",
		// and a renamed student would show their old name until their next
		// submission.
		if err := r.GamificationClient.UpdateLeaderboard(ctx, payload.User.ID, payload.User.FullName, "", payload.User.Grade); err != nil {
			slog.Warn("could not refresh leaderboard identity on login",
				slog.String("user_id", payload.User.ID), slog.Any("error", err))
		}
		if totalXp, err := r.GamificationClient.GetUserXp(ctx, payload.User.ID); err == nil {
			payload.User.TotalXp = totalXp
		}
	}

	return payload, nil
}

// GoogleLogin is the resolver for the googleLogin field.
func (r *mutationResolver) GoogleLogin(ctx context.Context, input model.GoogleLoginInput) (*model.AuthPayload, error) {
	payload, err := r.AuthClient.GoogleLogin(ctx, input)
	if err != nil {
		return nil, err
	}
	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)

	// Attach streak/XP exactly like the email/password Login path so the client
	// doesn't render 0 XP until the first `me` query.
	if payload.User != nil {
		if streak, err := r.GamificationClient.GetUserStreak(ctx, payload.User.ID); err == nil {
			payload.User.Streak = streak.Current
			payload.User.LongestStreak = streak.Longest
			payload.User.LastActiveAt = streak.LastActiveAt
		}
		if err := r.GamificationClient.UpdateLeaderboard(ctx, payload.User.ID, payload.User.FullName, "", payload.User.Grade); err != nil {
			slog.Warn("could not refresh leaderboard identity on login",
				slog.String("user_id", payload.User.ID), slog.Any("error", err))
		}
		if totalXp, err := r.GamificationClient.GetUserXp(ctx, payload.User.ID); err == nil {
			payload.User.TotalXp = totalXp
		}
	}

	return payload, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	if refreshToken == "" {
		req, ok := middleware.RequestFromContext(ctx)
		if ok {
			if cookie, err := req.Cookie("refresh_token"); err == nil {
				refreshToken = cookie.Value
			}
		}
	}

	if refreshToken == "" {
		return nil, errors.New("refresh token is required")
	}

	payload, err := r.AuthClient.RefreshToken(ctx, refreshToken)
	if err != nil {
		return nil, err
	}

	setAuthCookies(ctx, payload.AccessToken, payload.RefreshToken)
	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	w, ok := middleware.ResponseWriterFromContext(ctx)
	if !ok {
		return true, nil
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "access_token",
		Value:    "",
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
		MaxAge:   -1,
	})

	http.SetCookie(w, &http.Cookie{
		Name:     "refresh_token",
		Value:    "",
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
		MaxAge:   -1,
	})

	return true, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CreateCourseInput) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateCourse(ctx, userCtx.UserID, input)
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, id string, input model.UpdateCourseInput) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateCourse(ctx, userCtx.UserID, id, input)
}

// PublishCourse is the resolver for the publishCourse field.
func (r *mutationResolver) PublishCourse(ctx context.Context, id string) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishCourse(ctx, userCtx.UserID, id)
}

// DeleteCourse is the resolver for the deleteCourse field.
func (r *mutationResolver) DeleteCourse(ctx context.Context, id string) (bool, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	if err := requireEducator(userCtx); err != nil {
		return false, err
	}

	if err := r.CourseClient.DeleteCourse(ctx, userCtx.UserID, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateLesson is the resolver for the createLesson field.
func (r *mutationResolver) CreateLesson(ctx context.Context, courseID string, input model.CreateLessonInput) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateLesson(ctx, userCtx.UserID, courseID, input)
}

// UpdateLesson is the resolver for the updateLesson field.
func (r *mutationResolver) UpdateLesson(ctx context.Context, id string, input model.UpdateLessonInput) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateLesson(ctx, userCtx.UserID, id, input)
}

// PublishLesson is the resolver for the publishLesson field.
func (r *mutationResolver) PublishLesson(ctx context.Context, id string) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishLesson(ctx, userCtx.UserID, id)
}

// DeleteLesson is the resolver for the deleteLesson field.
func (r *mutationResolver) DeleteLesson(ctx context.Context, id string) (bool, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	if err := requireEducator(userCtx); err != nil {
		return false, err
	}

	if err := r.CourseClient.DeleteLesson(ctx, userCtx.UserID, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateWave is the resolver for the createWave field.
func (r *mutationResolver) CreateWave(ctx context.Context, lessonID string, input model.CreateWaveInput) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.CreateWave(ctx, userCtx.UserID, lessonID, input)
}

// UpdateWave is the resolver for the updateWave field.
func (r *mutationResolver) UpdateWave(ctx context.Context, id string, input model.UpdateWaveInput) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.UpdateWave(ctx, userCtx.UserID, id, input)
}

// PublishWave is the resolver for the publishWave field.
func (r *mutationResolver) PublishWave(ctx context.Context, id string) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}

	return r.CourseClient.PublishWave(ctx, userCtx.UserID, id)
}

// DeleteWave is the resolver for the deleteWave field.
func (r *mutationResolver) DeleteWave(ctx context.Context, id string) (bool, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	if err := requireEducator(userCtx); err != nil {
		return false, err
	}

	if err := r.CourseClient.DeleteWave(ctx, userCtx.UserID, id); err != nil {
		return false, err
	}
	return true, nil
}

// SubmitWaveAnswers is the resolver for the submitWaveAnswers field.
func (r *mutationResolver) SubmitWaveAnswers(ctx context.Context, waveID string, answers []*model.AnswerInput, submissionID *string) (*model.WaveResult, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	result, err := r.ProgressClient.SubmitWaveAnswers(ctx, userCtx.UserID, waveID, answers, submissionID)
	if err != nil {
		return nil, err
	}

	if result.Passed {
		// Everything below is a side effect of a submission that is already
		// durable. None of it may fail the student's result: losing a graded
		// attempt to a Redis blip is far worse than a stale leaderboard.
		courseID, err := r.CourseClient.GetWaveCourseID(ctx, waveID)
		if err != nil {
			slog.Warn("could not resolve the wave's course for ranking",
				slog.String("wave_id", waveID), slog.Any("error", err))
		}

		var grade *model.Grade
		if authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID); err == nil {
			grade = authUser.Grade
		}

		// One call refreshes every scope the student stands on. The display
		// name is stored unmasked and masked on read, so an educator view can
		// later be granted real names without a data migration.
		if err := r.GamificationClient.UpdateLeaderboard(ctx, userCtx.UserID, userCtx.FullName, courseID, grade); err != nil {
			slog.Error("leaderboard update failed after a passed wave",
				slog.String("user_id", userCtx.UserID), slog.Any("error", err))
		}

		r.publishWaveEvents(ctx, userCtx, waveID, courseID, result)
	}

	return result, nil
}

// ResetWaveAttempts is the resolver for the resetWaveAttempts field.
func (r *mutationResolver) ResetWaveAttempts(ctx context.Context, waveID string) (bool, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	return r.ProgressClient.ResetWaveAttempts(ctx, userCtx.UserID, waveID)
}

// EnrollInCourse is the resolver for the enrollInCourse field.
func (r *mutationResolver) EnrollInCourse(ctx context.Context, courseID string) (*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	course, err := r.CourseClient.GetCourseWithLessons(ctx, courseID)
	if err != nil {
		return nil, err
	}

	// Allow student enrollment in any course, removing restrictive grade mismatch check
	if userCtx.Role == "STUDENT" {
		_, err := r.AuthClient.GetUser(ctx, userCtx.UserID)
		if err != nil {
			return nil, fmt.Errorf("failed to verify student profile: %w", err)
		}
	}

	if _, err := r.ProgressClient.EnrollInCourse(ctx, userCtx.UserID, courseID); err != nil {
		return nil, err
	}

	progress, err := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, courseID)
	if err != nil {
		return nil, fmt.Errorf("failed to load progress: %w", err)
	}

	course.MyProgress = progress

	return course, nil
}

// GenerateLearnBlocks is the resolver for the generateLearnBlocks field.
func (r *mutationResolver) GenerateLearnBlocks(ctx context.Context, prompt string, language *string, grade *model.Grade) ([]*model.LearnBlock, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}
	if r.AIClient == nil {
		return nil, errors.New("AI service is not configured")
	}

	return r.AIClient.GenerateLearnBlocks(ctx, prompt, language, grade)
}

// GenerateEvaluateBlocks is the resolver for the generateEvaluateBlocks field.
func (r *mutationResolver) GenerateEvaluateBlocks(ctx context.Context, content string, count *int) ([]*model.EvaluateBlock, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := requireEducator(userCtx); err != nil {
		return nil, err
	}
	if r.AIClient == nil {
		return nil, errors.New("AI service is not configured")
	}

	return r.AIClient.GenerateEvaluateBlocks(ctx, content, count)
}

// TranslateContent is the resolver for the translateContent field.
func (r *mutationResolver) TranslateContent(ctx context.Context, content string, targetLanguage string) (string, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return "", err
	}
	if err := requireEducator(userCtx); err != nil {
		return "", err
	}
	if r.AIClient == nil {
		return "", errors.New("AI service is not configured")
	}

	return r.AIClient.TranslateContent(ctx, content, targetLanguage)
}

// GenerateVisualization is the resolver for the generateVisualization field.
func (r *mutationResolver) GenerateVisualization(ctx context.Context, concept string, vizType model.VizType, grade *string) (string, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return "", err
	}
	if err := requireEducator(userCtx); err != nil {
		return "", err
	}
	if r.AIClient == nil {
		return "", errors.New("AI service is not configured")
	}

	gradeValue := ""
	if grade != nil {
		gradeValue = *grade
	}
	return r.AIClient.GenerateVisualization(ctx, concept, vizTypeToService(vizType), gradeValue)
}

// AnalyzeImage is the resolver for the analyzeImage field.
func (r *mutationResolver) AnalyzeImage(ctx context.Context, imageBase64 string, prompt *string) (string, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return "", err
	}
	if err := requireEducator(userCtx); err != nil {
		return "", err
	}
	if r.AIClient == nil {
		return "", errors.New("AI service is not configured")
	}

	promptValue := ""
	if prompt != nil {
		promptValue = *prompt
	}
	return r.AIClient.AnalyzeImage(ctx, imageBase64, promptValue)
}

// CreateSubscription is the resolver for the createSubscription field.
func (r *mutationResolver) CreateSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.UserSubscription, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.PaymentClient == nil {
		return nil, errors.New("payments are not configured")
	}

	return r.PaymentClient.CreateSubscription(ctx, userCtx.UserID, input.Tier)
}

// CancelSubscription is the resolver for the cancelSubscription field.
func (r *mutationResolver) CancelSubscription(ctx context.Context) (*model.UserSubscription, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.PaymentClient == nil {
		return nil, errors.New("payments are not configured")
	}

	return r.PaymentClient.CancelSubscription(ctx, userCtx.UserID)
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateMeInput) (*model.User, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedUser, err := r.AuthClient.UpdateUser(ctx, userCtx.UserID, input)
	if err != nil {
		return nil, err
	}

	// Fetch XP & Streaks to populate model fully
	// A gamification outage must not fail `me` — the rest of the session still
	// works — but it must not read as a silent "0 XP" either, so it is logged.
	totalXp, err := r.GamificationClient.GetUserXp(ctx, userCtx.UserID)
	if err != nil {
		slog.Warn("could not read total xp for me", slog.String("user_id", userCtx.UserID), slog.Any("error", err))
	}
	streak, err := r.GamificationClient.GetUserStreak(ctx, userCtx.UserID)
	if err != nil {
		slog.Warn("could not read streak for me", slog.String("user_id", userCtx.UserID), slog.Any("error", err))
	}
	updatedUser.TotalXp = totalXp
	updatedUser.Streak = streak.Current
	updatedUser.LongestStreak = streak.Longest
	updatedUser.LastActiveAt = streak.LastActiveAt

	return updatedUser, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userCtx, ok := middleware.UserFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	// A gamification outage must not fail `me` — the rest of the session still
	// works — but it must not read as a silent "0 XP" either, so it is logged.
	totalXp, err := r.GamificationClient.GetUserXp(ctx, userCtx.UserID)
	if err != nil {
		slog.Warn("could not read total xp for me", slog.String("user_id", userCtx.UserID), slog.Any("error", err))
	}
	streak, err := r.GamificationClient.GetUserStreak(ctx, userCtx.UserID)
	if err != nil {
		slog.Warn("could not read streak for me", slog.String("user_id", userCtx.UserID), slog.Any("error", err))
	}

	var grade *model.Grade
	if authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID); err == nil {
		grade = authUser.Grade
	}

	var subscription *model.UserSubscription
	if r.PaymentClient != nil {
		// A "not found" response just means the user never subscribed — not a hard error.
		if sub, err := r.PaymentClient.GetSubscription(ctx, userCtx.UserID); err == nil {
			subscription = sub
		}
	}

	return &model.User{
		ID:                userCtx.UserID,
		Email:             userCtx.Email,
		FullName:          userCtx.FullName,
		Role:              model.Role(userCtx.Role),
		Grade:             grade,
		PreferredLanguage: userCtx.PreferredLanguage,
		TotalXp:           totalXp,
		Streak:            streak.Current,
		LongestStreak:     streak.Longest,
		LastActiveAt:      streak.LastActiveAt,
		Subscription:      subscription,
	}, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context, filter *model.CourseFilter, pagination *model.PaginationInput) (*model.CourseConnection, error) {
	if filter == nil {
		filter = &model.CourseFilter{}
	}

	userCtx, ok := middleware.UserFromContext(ctx)
	isEducator := ok && (userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN")

	var educatorID string
	if ok && isEducator {
		educatorID = userCtx.UserID
	} else if filter.IsPublished == nil {
		published := true
		filter.IsPublished = &published
	}

	conn, err := r.CourseClient.ListCourses(ctx, filter, educatorID)
	if err != nil {
		return nil, err
	}
	courses := make([]*model.Course, 0, len(conn.Edges))
	for _, edge := range conn.Edges {
		if edge != nil {
			courses = append(courses, edge.Node)
		}
	}
	r.populateLessonsParallel(ctx, courses)
	return conn, nil
}

// MyEnrollments is the resolver for the myEnrollments field.
func (r *queryResolver) MyEnrollments(ctx context.Context) ([]*model.Course, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	courses, err := r.ProgressClient.GetEnrolledCourses(ctx, userCtx.UserID)
	if err != nil {
		return nil, err
	}

	r.populateLessonsParallel(ctx, courses)
	for _, course := range courses {
		progress, _ := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, course.ID)
		course.MyProgress = progress
	}
	r.populateWavesProgressParallel(ctx, userCtx.UserID, courses)

	return courses, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	userCtx, ok := middleware.UserFromContext(ctx)

	course, err := r.CourseClient.GetCourseWithLessons(ctx, id)
	if err != nil {
		return nil, err
	}

	isEducatorOrAdmin := ok && (userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN")
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own this course")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}

		// Enrollment check removed to allow viewing course details

		// Filter out unpublished lessons and waves
		publishedLessons := make([]*model.Lesson, 0, len(course.Lessons))
		for _, lesson := range course.Lessons {
			if lesson.IsPublished {
				publishedWaves := make([]*model.Wave, 0, len(lesson.Waves))
				for _, wave := range lesson.Waves {
					if wave.IsPublished {
						publishedWaves = append(publishedWaves, wave)
					}
				}
				lesson.Waves = publishedWaves
				publishedLessons = append(publishedLessons, lesson)
			}
		}
		course.Lessons = publishedLessons
		if ok {
			r.populateWavesProgressParallel(ctx, userCtx.UserID, []*model.Course{course})
		}
	}

	if ok {
		progress, _ := r.ProgressClient.GetCourseProgressSummary(ctx, userCtx.UserID, id)
		course.MyProgress = progress
	}

	return course, nil
}

// Lesson is the resolver for the lesson field.
func (r *queryResolver) Lesson(ctx context.Context, id string) (*model.Lesson, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	lesson, err := r.CourseClient.GetLessonWithWaves(ctx, id)
	if err != nil {
		return nil, err
	}

	if lesson.Course == nil {
		return nil, errors.New("lesson has no associated course")
	}

	course, err := r.CourseClient.GetCourse(ctx, lesson.Course.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve course for lesson: %w", err)
	}

	isEducatorOrAdmin := userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN"
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own the course for this lesson")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}
		if !lesson.IsPublished {
			return nil, errors.New("forbidden: lesson is not published")
		}

		enrolled, err := r.ProgressClient.IsEnrolled(ctx, userCtx.UserID, course.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to check enrollment: %w", err)
		}
		if !enrolled {
			return nil, errors.New("forbidden: not enrolled in the course for this lesson")
		}

		// Filter out unpublished waves
		publishedWaves := make([]*model.Wave, 0, len(lesson.Waves))
		for _, wave := range lesson.Waves {
			if wave.IsPublished {
				publishedWaves = append(publishedWaves, wave)
			}
		}
		lesson.Waves = publishedWaves
	}

	return lesson, nil
}

// Wave is the resolver for the wave field.
func (r *queryResolver) Wave(ctx context.Context, id string) (*model.Wave, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	wave, err := r.CourseClient.GetWave(ctx, id)
	if err != nil {
		return nil, err
	}

	if wave.Lesson == nil {
		return nil, errors.New("wave has no associated lesson")
	}

	lesson, err := r.CourseClient.GetLesson(ctx, wave.Lesson.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve lesson for wave: %w", err)
	}

	if lesson.Course == nil {
		return nil, errors.New("lesson has no associated course")
	}

	course, err := r.CourseClient.GetCourseWithLessons(ctx, lesson.Course.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve course for wave: %w", err)
	}

	isEducatorOrAdmin := userCtx.Role == "EDUCATOR" || userCtx.Role == "HEAD_EDUCATOR" || userCtx.Role == "ADMIN"
	if isEducatorOrAdmin {
		if userCtx.Role != "ADMIN" {
			if course.Educator == nil || course.Educator.ID != userCtx.UserID {
				return nil, errors.New("forbidden: you do not own the course for this wave")
			}
		}
	} else {
		// Student flow
		if !course.IsPublished {
			return nil, errors.New("forbidden: course is not published")
		}
		if !lesson.IsPublished {
			return nil, errors.New("forbidden: lesson is not published")
		}
		if !wave.IsPublished {
			return nil, errors.New("forbidden: wave is not published")
		}

		enrolled, err := r.ProgressClient.IsEnrolled(ctx, userCtx.UserID, course.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to check enrollment: %w", err)
		}
		if !enrolled {
			return nil, errors.New("forbidden: not enrolled in the course for this wave")
		}
	}

	progress, _ := r.ProgressClient.GetWaveProgress(ctx, userCtx.UserID, id)
	wave.MyProgress = progress
	lesson.Course = course
	wave.Lesson = lesson

	return wave, nil
}

// Progress is the resolver for the progress field.
func (r *queryResolver) Progress(ctx context.Context, courseID *string) ([]*model.LessonProgress, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	if courseID == nil || *courseID == "" {
		return nil, errors.New("course id is required")
	}

	return r.ProgressClient.GetCourseProgress(ctx, userCtx.UserID, *courseID)
}

// WaveProgress is the resolver for the waveProgress field.
func (r *queryResolver) WaveProgress(ctx context.Context, waveID string) (*model.WaveProgress, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	return r.ProgressClient.GetWaveProgress(ctx, userCtx.UserID, waveID)
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, scope model.LeaderboardScope, courseID *string, grade *model.Grade, limit *int, offset *int) (*model.LeaderboardPage, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	pageSize := int32(defaultLeaderboardPage)
	if limit != nil && *limit > 0 {
		pageSize = int32(*limit)
	}
	if pageSize > maxLeaderboardPage {
		pageSize = maxLeaderboardPage
	}
	var from int32
	if offset != nil && *offset > 0 {
		from = int32(*offset)
	}

	// The grade board defaults to the viewer's own grade rather than letting a
	// student browse other grades' boards by passing an arbitrary value.
	if scope == model.LeaderboardScopeGrade && grade == nil {
		if authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID); err == nil {
			grade = authUser.Grade
		}
	}

	entries, totalRanked, err := r.GamificationClient.GetLeaderboard(ctx, userCtx.UserID, scope, courseID, grade, pageSize, from)
	if err != nil {
		return nil, err
	}

	page := &model.LeaderboardPage{Entries: entries, TotalRanked: totalRanked}

	// A student outside the page still needs to see where they stand, which is
	// the whole point of a leaderboard for the other 99% of users.
	for _, entry := range entries {
		if entry.IsMe {
			page.Me = entry
			break
		}
	}
	if page.Me == nil {
		rank, totalXp, _, err := r.GamificationClient.GetMyRank(ctx, userCtx.UserID, scope, courseID, grade)
		if err != nil {
			slog.Warn("could not resolve the viewer's rank",
				slog.String("user_id", userCtx.UserID), slog.Any("error", err))
		} else if rank > 0 {
			page.Me = &model.LeaderboardEntry{
				Rank:        rank,
				UserID:      userCtx.UserID,
				DisplayName: client.MaskDisplayName(userCtx.FullName),
				TotalXp:     totalXp,
				IsMe:        true,
			}
		}
	}

	return page, nil
}

// MyRank is the resolver for the myRank field.
func (r *queryResolver) MyRank(ctx context.Context, scope model.LeaderboardScope, courseID *string) (*int, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var grade *model.Grade
	if scope == model.LeaderboardScopeGrade {
		authUser, err := r.AuthClient.GetUser(ctx, userCtx.UserID)
		if err != nil {
			return nil, err
		}
		grade = authUser.Grade
	}

	rank, _, _, err := r.GamificationClient.GetMyRank(ctx, userCtx.UserID, scope, courseID, grade)
	if err != nil {
		return nil, err
	}
	// Unranked reads as null, not as rank zero.
	if rank == 0 {
		return nil, nil
	}

	return &rank, nil
}

// Achievements is the resolver for the achievements field.
func (r *queryResolver) Achievements(ctx context.Context) ([]*model.Achievement, error) {
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	return r.GamificationClient.GetAchievements(ctx, userCtx.UserID)
}

// LeaderboardUpdated is the resolver for the leaderboardUpdated field.
func (r *subscriptionResolver) LeaderboardUpdated(ctx context.Context, scope model.LeaderboardScope, courseID *string) (<-chan *model.LeaderboardEntry, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	viewer, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.LeaderboardUpdatedEvent](ctx, r.Events, events.ChannelLeaderboard)
	out := make(chan *model.LeaderboardEntry, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.Scope != string(scope) {
				continue
			}
			if scope == model.LeaderboardScopeCourse && (courseID == nil || e.CourseID != *courseID) {
				continue
			}
			out <- &model.LeaderboardEntry{
				Rank:        int(e.Rank),
				UserID:      e.UserID,
				DisplayName: client.MaskDisplayName(e.FullName),
				TotalXp:     int(e.TotalXp),
				IsMe:        e.UserID == viewer.UserID,
			}
		}
	}()
	return out, nil
}

// XpGained is the resolver for the xpGained field.
func (r *subscriptionResolver) XpGained(ctx context.Context) (<-chan *model.XpEvent, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.XpAwardedEvent](ctx, r.Events, events.ChannelXp)
	out := make(chan *model.XpEvent, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			out <- &model.XpEvent{
				WaveID:  e.SourceID,
				Amount:  int(e.Amount),
				TotalXp: int(e.TotalXp),
				Reason:  e.Reason,
			}
		}
	}()
	return out, nil
}

// AchievementUnlocked is the resolver for the achievementUnlocked field.
func (r *subscriptionResolver) AchievementUnlocked(ctx context.Context) (<-chan *model.Achievement, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.AchievementUnlockedEvent](ctx, r.Events, events.ChannelAchievement)
	out := make(chan *model.Achievement, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			// An unlock event only ever describes an achievement that has
			// just been earned, so it is always unlocked.
			unlockedAt := time.Unix(e.UnlockedAtUnix, 0)
			achievement := &model.Achievement{
				ID:          e.ID,
				Name:        e.Name,
				Description: e.Description,
				Unlocked:    true,
				UnlockedAt:  &unlockedAt,
			}
			if e.IconURL != "" {
				iconURL := e.IconURL
				achievement.IconURL = &iconURL
			}
			out <- achievement
		}
	}()
	return out, nil
}

// WaveCompleted is the resolver for the waveCompleted field.
func (r *subscriptionResolver) WaveCompleted(ctx context.Context) (<-chan *model.WaveProgress, error) {
	if r.Events == nil {
		return nil, errors.New("real-time events are not configured")
	}
	userCtx, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	source := events.SubscribeJSON[events.WaveCompletedEvent](ctx, r.Events, events.ChannelWaveCompleted)
	out := make(chan *model.WaveProgress, 1)
	go func() {
		defer close(out)
		for e := range source {
			if e.UserID != userCtx.UserID {
				continue
			}
			score := int(e.Score)
			completedAt := time.Unix(e.CompletedAtUnix, 0)
			out <- &model.WaveProgress{
				Status:       model.ProgressStatusCompleted,
				HighestScore: &score,
				CompletedAt:  &completedAt,
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
