apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studed.name" . }}-secrets
  labels:
    {{- include "studed.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
