apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: studed
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: studed-doc-course-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: studed-config
            - secretRef:
                name: studed-secrets
          resources:
            requests:
              memory: "15Mi"
              cpu: "10m"
            limits:
              memory: "48Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: studed
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: grpc
    - port: 8084
      targetPort: 8084
      name: http
  selector:
    app: course-service
