// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Achievement struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IconURL     *string   `json:"iconUrl,omitempty"`
	UnlockedAt  time.Time `json:"unlockedAt"`
}

type AnswerInput struct {
	EvaluateBlockID string `json:"evaluateBlockId"`
	Answer          string `json:"answer"`
}

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Course struct {
	ID          string          `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Slug        string          `json:"slug"`
	GradeLevel  Grade           `json:"gradeLevel"`
	Educator    *User           `json:"educator"`
	Price       *float64        `json:"price,omitempty"`
	IsPublished bool            `json:"isPublished"`
	Lessons     []*Lesson       `json:"lessons"`
	MyProgress  *CourseProgress `json:"myProgress,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
}

type CourseConnection struct {
	Edges    []*CourseEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type CourseEdge struct {
	Node   *Course `json:"node"`
	Cursor string  `json:"cursor"`
}

type CourseFilter struct {
	Grade       *Grade  `json:"grade,omitempty"`
	Subject     *string `json:"subject,omitempty"`
	Search      *string `json:"search,omitempty"`
	IsPublished *bool   `json:"isPublished,omitempty"`
}

type CourseProgress struct {
	CompletedWaves int        `json:"completedWaves"`
	TotalWaves     int        `json:"totalWaves"`
	StartedAt      *time.Time `json:"startedAt,omitempty"`
	CompletedAt    *time.Time `json:"completedAt,omitempty"`
}

type CreateCourseInput struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Slug        string   `json:"slug"`
	GradeLevel  Grade    `json:"gradeLevel"`
	Price       *float64 `json:"price,omitempty"`
}

type CreateLessonInput struct {
	Title         string `json:"title"`
	SequenceOrder int    `json:"sequenceOrder"`
}

type CreateSubscriptionInput struct {
	Tier Tier `json:"tier"`
}

type CreateWaveInput struct {
	Title             string                `json:"title"`
	SequenceOrder     int                   `json:"sequenceOrder"`
	XpReward          int                   `json:"xpReward"`
	MaxReattempts     int                   `json:"maxReattempts"`
	PassingThreshold  int                   `json:"passingThreshold"`
	EstimatedDuration int                   `json:"estimatedDuration"`
	Difficulty        Difficulty            `json:"difficulty"`
	LearnBlocks       []*LearnBlockInput    `json:"learnBlocks,omitempty"`
	EvaluateBlocks    []*EvaluateBlockInput `json:"evaluateBlocks,omitempty"`
}

type EvaluateBlock struct {
	ID            string   `json:"id"`
	Type          string   `json:"type"`
	Question      string   `json:"question"`
	Options       []string `json:"options,omitempty"`
	CorrectAnswer *string  `json:"correctAnswer,omitempty"`
	Explanation   *string  `json:"explanation,omitempty"`
	Metadata      *string  `json:"metadata,omitempty"`
}

type EvaluateBlockInput struct {
	ID            string   `json:"id"`
	Type          string   `json:"type"`
	Question      string   `json:"question"`
	Options       []string `json:"options,omitempty"`
	CorrectAnswer *string  `json:"correctAnswer,omitempty"`
	Explanation   *string  `json:"explanation,omitempty"`
	Metadata      *string  `json:"metadata,omitempty"`
}

type LeaderboardEntry struct {
	Rank    int     `json:"rank"`
	User    *User   `json:"user"`
	TotalXp int     `json:"totalXp"`
	Course  *Course `json:"course,omitempty"`
}

type LearnBlock struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	Content  string  `json:"content"`
	Metadata *string `json:"metadata,omitempty"`
}

type LearnBlockInput struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	Content  string  `json:"content"`
	Metadata *string `json:"metadata,omitempty"`
}

type Lesson struct {
	ID            string  `json:"id"`
	Course        *Course `json:"course"`
	Title         string  `json:"title"`
	SequenceOrder int     `json:"sequenceOrder"`
	Waves         []*Wave `json:"waves"`
	IsPublished   bool    `json:"isPublished"`
}

type LessonProgress struct {
	Lesson         *Lesson `json:"lesson"`
	CompletedWaves int     `json:"completedWaves"`
	TotalWaves     int     `json:"totalWaves"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	First *int    `json:"first,omitempty"`
	After *string `json:"after,omitempty"`
}

type Query struct {
}

type QuestionFeedback struct {
	EvaluateBlockID string  `json:"evaluateBlockId"`
	Correct         bool    `json:"correct"`
	CorrectAnswer   *string `json:"correctAnswer,omitempty"`
	Explanation     *string `json:"explanation,omitempty"`
}

type RegisterInput struct {
	Email             string  `json:"email"`
	Password          string  `json:"password"`
	FullName          string  `json:"fullName"`
	Role              Role    `json:"role"`
	Grade             *Grade  `json:"grade,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type Subscription struct {
}

type UpdateCourseInput struct {
	Title       *string  `json:"title,omitempty"`
	Description *string  `json:"description,omitempty"`
	Slug        *string  `json:"slug,omitempty"`
	GradeLevel  *Grade   `json:"gradeLevel,omitempty"`
	Price       *float64 `json:"price,omitempty"`
}

type UpdateLessonInput struct {
	Title         *string `json:"title,omitempty"`
	SequenceOrder *int    `json:"sequenceOrder,omitempty"`
}

type UpdateMeInput struct {
	FullName          *string `json:"fullName,omitempty"`
	Grade             *Grade  `json:"grade,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type UpdateWaveInput struct {
	Title             *string               `json:"title,omitempty"`
	SequenceOrder     *int                  `json:"sequenceOrder,omitempty"`
	XpReward          *int                  `json:"xpReward,omitempty"`
	MaxReattempts     *int                  `json:"maxReattempts,omitempty"`
	PassingThreshold  *int                  `json:"passingThreshold,omitempty"`
	EstimatedDuration *int                  `json:"estimatedDuration,omitempty"`
	Difficulty        *Difficulty           `json:"difficulty,omitempty"`
	LearnBlocks       []*LearnBlockInput    `json:"learnBlocks,omitempty"`
	EvaluateBlocks    []*EvaluateBlockInput `json:"evaluateBlocks,omitempty"`
}

type User struct {
	ID                string            `json:"id"`
	Email             string            `json:"email"`
	FullName          string            `json:"fullName"`
	Role              Role              `json:"role"`
	Grade             *Grade            `json:"grade,omitempty"`
	PreferredLanguage string            `json:"preferredLanguage"`
	Subscription      *UserSubscription `json:"subscription,omitempty"`
	TotalXp           int               `json:"totalXp"`
	Streak            int               `json:"streak"`
	CreatedAt         time.Time         `json:"createdAt"`
}

type UserSubscription struct {
	ID        string             `json:"id"`
	Tier      Tier               `json:"tier"`
	Status    SubscriptionStatus `json:"status"`
	StartDate time.Time          `json:"startDate"`
	EndDate   time.Time          `json:"endDate"`
}

type Wave struct {
	ID                string           `json:"id"`
	Lesson            *Lesson          `json:"lesson"`
	Title             string           `json:"title"`
	SequenceOrder     int              `json:"sequenceOrder"`
	XpReward          int              `json:"xpReward"`
	MaxReattempts     int              `json:"maxReattempts"`
	PassingThreshold  int              `json:"passingThreshold"`
	EstimatedDuration int              `json:"estimatedDuration"`
	Difficulty        Difficulty       `json:"difficulty"`
	LearnBlocks       []*LearnBlock    `json:"learnBlocks"`
	EvaluateBlocks    []*EvaluateBlock `json:"evaluateBlocks"`
	MyProgress        *WaveProgress    `json:"myProgress,omitempty"`
	IsPublished       bool             `json:"isPublished"`
}

type WaveProgress struct {
	Status          ProgressStatus `json:"status"`
	AttemptsCount   int            `json:"attemptsCount"`
	HighestScore    *int           `json:"highestScore,omitempty"`
	CompletedAt     *time.Time     `json:"completedAt,omitempty"`
	LastAttemptedAt *time.Time     `json:"lastAttemptedAt,omitempty"`
}

type WaveResult struct {
	Score             int                 `json:"score"`
	XpEarned          int                 `json:"xpEarned"`
	TotalXp           int                 `json:"totalXp"`
	Passed            bool                `json:"passed"`
	RemainingAttempts *int                `json:"remainingAttempts,omitempty"`
	Feedback          []*QuestionFeedback `json:"feedback"`
}

type XpEvent struct {
	WaveID  string `json:"waveId"`
	Amount  int    `json:"amount"`
	TotalXp int    `json:"totalXp"`
	Reason  string `json:"reason"`
}

type Difficulty string

const (
	DifficultyEasy   Difficulty = "EASY"
	DifficultyMedium Difficulty = "MEDIUM"
	DifficultyHard   Difficulty = "HARD"
)

var AllDifficulty = []Difficulty{
	DifficultyEasy,
	DifficultyMedium,
	DifficultyHard,
}

func (e Difficulty) IsValid() bool {
	switch e {
	case DifficultyEasy, DifficultyMedium, DifficultyHard:
		return true
	}
	return false
}

func (e Difficulty) String() string {
	return string(e)
}

func (e *Difficulty) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Difficulty(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Difficulty", str)
	}
	return nil
}

func (e Difficulty) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Difficulty) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Difficulty) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Grade string

const (
	GradeG1  Grade = "G1"
	GradeG2  Grade = "G2"
	GradeG3  Grade = "G3"
	GradeG4  Grade = "G4"
	GradeG5  Grade = "G5"
	GradeG6  Grade = "G6"
	GradeG7  Grade = "G7"
	GradeG8  Grade = "G8"
	GradeG9  Grade = "G9"
	GradeG10 Grade = "G10"
	GradeG11 Grade = "G11"
	GradeOl  Grade = "OL"
	GradeAl  Grade = "AL"
)

var AllGrade = []Grade{
	GradeG1,
	GradeG2,
	GradeG3,
	GradeG4,
	GradeG5,
	GradeG6,
	GradeG7,
	GradeG8,
	GradeG9,
	GradeG10,
	GradeG11,
	GradeOl,
	GradeAl,
}

func (e Grade) IsValid() bool {
	switch e {
	case GradeG1, GradeG2, GradeG3, GradeG4, GradeG5, GradeG6, GradeG7, GradeG8, GradeG9, GradeG10, GradeG11, GradeOl, GradeAl:
		return true
	}
	return false
}

func (e Grade) String() string {
	return string(e)
}

func (e *Grade) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Grade(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Grade", str)
	}
	return nil
}

func (e Grade) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Grade) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Grade) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LeaderboardScope string

const (
	LeaderboardScopeGlobal LeaderboardScope = "GLOBAL"
	LeaderboardScopeCourse LeaderboardScope = "COURSE"
	LeaderboardScopeGrade  LeaderboardScope = "GRADE"
)

var AllLeaderboardScope = []LeaderboardScope{
	LeaderboardScopeGlobal,
	LeaderboardScopeCourse,
	LeaderboardScopeGrade,
}

func (e LeaderboardScope) IsValid() bool {
	switch e {
	case LeaderboardScopeGlobal, LeaderboardScopeCourse, LeaderboardScopeGrade:
		return true
	}
	return false
}

func (e LeaderboardScope) String() string {
	return string(e)
}

func (e *LeaderboardScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LeaderboardScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LeaderboardScope", str)
	}
	return nil
}

func (e LeaderboardScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LeaderboardScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LeaderboardScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProgressStatus string

const (
	ProgressStatusLocked    ProgressStatus = "LOCKED"
	ProgressStatusAvailable ProgressStatus = "AVAILABLE"
	ProgressStatusStarted   ProgressStatus = "STARTED"
	ProgressStatusCompleted ProgressStatus = "COMPLETED"
)

var AllProgressStatus = []ProgressStatus{
	ProgressStatusLocked,
	ProgressStatusAvailable,
	ProgressStatusStarted,
	ProgressStatusCompleted,
}

func (e ProgressStatus) IsValid() bool {
	switch e {
	case ProgressStatusLocked, ProgressStatusAvailable, ProgressStatusStarted, ProgressStatusCompleted:
		return true
	}
	return false
}

func (e ProgressStatus) String() string {
	return string(e)
}

func (e *ProgressStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgressStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgressStatus", str)
	}
	return nil
}

func (e ProgressStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProgressStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProgressStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleStudent      Role = "STUDENT"
	RoleEducator     Role = "EDUCATOR"
	RoleHeadEducator Role = "HEAD_EDUCATOR"
	RoleAdmin        Role = "ADMIN"
)

var AllRole = []Role{
	RoleStudent,
	RoleEducator,
	RoleHeadEducator,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleStudent, RoleEducator, RoleHeadEducator, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive   SubscriptionStatus = "ACTIVE"
	SubscriptionStatusCanceled SubscriptionStatus = "CANCELED"
	SubscriptionStatusExpired  SubscriptionStatus = "EXPIRED"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusActive,
	SubscriptionStatusCanceled,
	SubscriptionStatusExpired,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusCanceled, SubscriptionStatusExpired:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Tier string

const (
	TierBasic    Tier = "BASIC"
	TierStandard Tier = "STANDARD"
	TierPremium  Tier = "PREMIUM"
	TierSchool   Tier = "SCHOOL"
)

var AllTier = []Tier{
	TierBasic,
	TierStandard,
	TierPremium,
	TierSchool,
}

func (e Tier) IsValid() bool {
	switch e {
	case TierBasic, TierStandard, TierPremium, TierSchool:
		return true
	}
	return false
}

func (e Tier) String() string {
	return string(e)
}

func (e *Tier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tier", str)
	}
	return nil
}

func (e Tier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Tier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Tier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
